### ISSUE TITLE
Binary search tree Java implementation is not in list

### ISSUE THREAD

**Issue by wasifferoze** [NITSkmOS/Algorithms#484] opened 2018-10-29 22:35 UTC

**Comment by sangamcse** [comment] 2018-10-29 22:36
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/43 ([Algo] Binary Search [Python]), https://github.com/NITSkmOS/Algorithms/issues/51 ([Data Structure] Binary Search Tree [Python]), https://github.com/NITSkmOS/Algorithms/issues/234 ([Data Structure] Skip List [Python]), https://github.com/NITSkmOS/Algorithms/issues/188 (binary-search in c), and https://github.com/NITSkmOS/Algorithms/issues/50 ([Data Structure] AVL Tree [Python]).

**Comment by wasifferoze** [comment] 2018-10-29 22:36
please assign to me. I want to work on this

**Comment by sangamcse** [comment] 2018-10-30 02:38
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/52

**Closed by sangamcse** 2018-10-30 02:38 UTC
Labels: difficulty/low, hacktoberfest, lang/Python, type/data structure
