### ISSUE TITLE
euclidean_gcd in c++

### ISSUE THREAD

**Issue by thakurdivyanshu** [NITSkmOS/Algorithms#186] opened 2018-10-02 17:50 UTC
euclidean__gcd is there in c & java only. It should be there in c++ as well !!

**Comment by thakurdivyanshu** [comment] 2018-10-02 17:51
can i work on this??

**Comment by sangamcse** [comment] 2018-10-02 17:51
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/16 ([Algo]: Add euclidean-gcd in C++), https://github.com/NITSkmOS/Algorithms/issues/20 ([Algo]: Add Bubble Sort in C++), https://github.com/NITSkmOS/Algorithms/issues/41 ([DataStructure] Stack [C++]), https://github.com/NITSkmOS/Algorithms/issues/27 ([DataStructure] Linear Linked List [C++]), and https://github.com/NITSkmOS/Algorithms/issues/32 ([DataStructure] Doubly Linked List [C++]).

**Comment by sangamcse** [comment] 2018-10-02 22:40
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/16

**Closed by sangamcse** 2018-10-02 22:40 UTC
Labels: duplicate
