### ISSUE TITLE
[Algo] Heap sort [java]

### ISSUE THREAD

**Issue by pentalpha** [NITSkmOS/Algorithms#508] opened 2018-10-30 23:56 UTC
This repository is missing a Heap sort implementation using Java.

**Comment by pentalpha** [comment] 2018-10-30 23:57
I wish to be assigned to this issue

**Comment by sangamcse** [comment] 2018-10-30 23:58
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/451 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo] Heapsort [C]), https://github.com/NITSkmOS/Algorithms/issues/379 ([Algo] Counting Sort [java]), and https://github.com/NITSkmOS/Algorithms/issues/150 ([Algo] Quick Sort [Java]).

**Comment by sangamcse** [comment] 2018-10-31 11:04
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/21

**Closed** 2018-10-31 11:06 UTC
Labels: bug, difficulty/low, hacktoberfest, lang/Java, type/algo
