### ISSUE TITLE
binary-search in c

### ISSUE THREAD

**Issue by thakurdivyanshu** [NITSkmOS/Algorithms#188] opened 2018-10-02 18:08 UTC
Binary search is implemented only in c++ and java so, it will be good to have implementation in c as well !!

**Comment by sangamcse** [comment] 2018-10-02 18:09
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/44 ([Algo] Binary Search [C]), https://github.com/NITSkmOS/Algorithms/issues/40 ([DataStructure] Stack [C]), https://github.com/NITSkmOS/Algorithms/issues/53 ([Data Structure] Binary Search Tree [C]), https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]).

**Comment by Tchinmai7** [comment] 2018-10-02 18:11
I'll take this

**Comment by sangamcse** [comment] 2018-10-02 22:39
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/44

**Closed by sangamcse** 2018-10-02 22:39 UTC
Labels: duplicate
