### ISSUE TITLE
[Algo] Merge Sort (Java Implementation)

### ISSUE THREAD

**Issue by sameerchoubey** [NITSkmOS/Algorithms#281] opened 2018-10-04 16:34 UTC
Please assign this to me.

**Comment by sangamcse** [comment] 2018-10-04 16:35
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/149 ([Algo] Merge Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/223 ([Algo] Selection Sort [java]), https://github.com/NITSkmOS/Algorithms/issues/153 ([Algo] Insertion Sort [Java]), https://github.com/NITSkmOS/Algorithms/issues/63 ([Algo] Insertion Sort [Java]), and https://github.com/NITSkmOS/Algorithms/issues/46 ([Algo] Binary Search [Java]).

**Comment by sangamcse** [comment] 2018-10-04 17:10
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/149

**Closed by sangamcse** 2018-10-04 17:10 UTC
Labels: difficulty/low, hacktoberfest, type/algo
