### ISSUE TITLE
[Algo] Heap Sort [CPP]

### ISSUE THREAD

**Issue by 123vivekr** [NITSkmOS/Algorithms#422] opened 2018-10-09 15:53 UTC
https://en.wikipedia.org/wiki/Heapsort

**Comment by 123vivekr** [comment] 2018-10-09 15:53
@sangamcse Please assign this to me.

**Comment by sangamcse** [comment] 2018-10-09 15:54
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo]: Add Heapsort in C), https://github.com/NITSkmOS/Algorithms/issues/135 ([Algo] Shell Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/146 ([Algo] Quick Sort [C]).

**Comment by sangamcse** [comment] 2018-10-12 16:17
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/22

**Closed by sangamcse** 2018-10-12 16:17 UTC
Labels: difficulty/low, enhancement, hacktoberfest, lang/C, type/algo
