### ISSUE TITLE
[Algo] Heap Sort [C]

### ISSUE THREAD

**Issue by LHenrique42** [NITSkmOS/Algorithms#423] opened 2018-10-09 16:52 UTC
https://en.wikipedia.org/wiki/Heapsort

**Comment by sangamcse** [comment] 2018-10-09 16:53
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/NITSkmOS/Algorithms/issues/422 ([Algo] Heap Sort [CPP]), https://github.com/NITSkmOS/Algorithms/issues/147 ([Algo] Merge Sort [C]), https://github.com/NITSkmOS/Algorithms/issues/23 ([Algo]: Add Heapsort in C), https://github.com/NITSkmOS/Algorithms/issues/135 ([Algo] Shell Sort [C]), and https://github.com/NITSkmOS/Algorithms/issues/145 ([Algo] Selection Sort [C]).

**Comment by sangamcse** [comment] 2018-10-12 16:13
Duplicate of https://github.com/NITSkmOS/Algorithms/issues/23

**Closed by sangamcse** 2018-10-12 16:13 UTC
Labels: difficulty/low, enhancement, hacktoberfest, lang/C, type/algo
